enum WindowsEvents {
  CART_DATA = 'CART_DATA',
  CART_HEADER = 'CART_HEADER',
  TOGGLE_CART_ASIDE = 'TOGGLE_CART_ASIDE',
  ADD_PRODUCT_IN_CART = 'ADD_PRODUCT_IN_CART',
  GET_CART_ID = 'GET_CART_ID',
  GET_SHOPPING_CART = 'GET_SHOPPING_CART',
  SIMULATE_ADD_PRODUCT = 'SIMULATE_ADD_PRODUCT',
  ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR',
  UPDATE_SHIPPING_CART = 'UPDATE_SHIPPING_CART',
  ANALYTICS = 'ANALYTICS',
  DISPATCH_GET_CART_ID = 'DISPATCH_GET_CART_ID',
  DISPATCH_GET_CART = 'DISPATCH_GET_CART',
  UPDATE_SHOPPING_CART = 'UPDATE_SHOPPING_CART',
  DISPATCH_SHOPPING_CART_WITHOUT_ITEMS = 'DISPATCH_SHOPPING_CART_WITHOUT_ITEMS',
  GET_SHOPPING_CART_ERROR = 'GET_SHOPPING_CART_ERROR',
  UPDATE_MINI_CART = 'UPDATE_MINI_CART',
  ADD_ITEM_SHOPPING_CART = 'ADD_ITEM_SHOPPING_CART',
  ON_CLICK_ADD_PRODUCT_TO_CART = 'on-click-add-product-to-cart',
  ON_CLICK_PRODUCT_CARD = 'on-click-product-card',
}

export default WindowsEvents;
